- name: Clonar el repositorio DevOps
  become_user: Ruben
  git:
    repo: "https://github.com/RPirela/DevOps.git"
    dest: "/home/Ruben/devops_2"
    update: yes  # Actualiza el repositorio si ya existe
    force: yes
  become: true
  tags: clone_repository
