- name: Install required packages  
  become_user: Ruben
  apt:
    name:
      - apt-transport-https  
      - ca-certificates  
      - curl  
      - software-properties-common  
    ignore_errors: yes
    state: present

- name: Add Docker GPG key  
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg  
    state: present

- name: Add Docker repository  
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable  
    state: present

- name: Install Docker  
  apt:
    name: docker-ce  
    state: latest

- name: Install Docker Compose  
  command: pip install docker-compose  
  when: ansible_distribution == "Ubuntu"
